### ISSUE TITLE
Ensure that kpack does a Rebuild and not a Rebase when the run-image/builder stack has changed

### ISSUE THREAD

**Issue by djoyahoy** [pivotal/kpack#162]
When the  ONLY the run image and builder stack change, kpack should perform a rebuild and not a rebase.

**Comment by ashwin-venkatesh** [comment]
Closed via #179

**Comment by cmoulliard** [comment]
- Is this feature documented ? 
- Can we enable or disable the rebuild of the images ? 
- Which images will be rebuild: stack and/or runtime images, images of the microservices used to build or run it ? If only the bild/run images are updated, how can we rebuild the microservices consuming them ?

**Comment by tylerphelan** [comment]
@cmoulliard

> * Is this feature documented ?

There aren't any kpack-specific docs around this, but `kpack` is an implementation of the Cloud Native Buildpacks platform specification which can be found [here](https://github.com/buildpacks/spec/blob/main/platform.md).

The relevant topic for this issue is mentioned here in [Run Image Rebasing](https://github.com/buildpacks/spec/blob/main/platform.md#run-image-rebasing). These docs mention:

> When a new stack version with the same stack ID is available, the app layers and launch layers SHOULD be rebased

In the context of this issue, the stack ID would have changed which means there is no guarantee the "microservice layers" can compile on the new stack/run image which means `kpack` needs to rebuild the final image instead of rebase.

> * Can we enable or disable the rebuild of the images ?

There is no way currently to disable the rebuild in favor of a rebase in the case of a new stack id. Could you elaborate on your use case for this feature?

> * Which images will be rebuild: stack and/or runtime images, images of the microservices used to build or run it ? If only the build/run images are updated, how can we rebuild the microservices consuming them ?

With the new stack and/or runtime image, the "microservice layers" (or "app layers" as we might say) would get rebuilt and these changes would propagate to your registry ready to use for runtime.

Hope this helps! Happy to clarify anything.

**Comment by tylerphelan** [comment]
you can also ask questions in buildpacks.slack.com #kpack channel
