### ISSUE TITLE
Handle JARs with `license/LICENSE` file

### ISSUE THREAD

**Issue by tylerphelan** [pivotal/kpack#468]
kpack fails to extract JAR files with `license/LICENSE` files.

This could be handled more gracefully.

Test Jar: https://uaa-migration-jars.s3-us-west-1.amazonaws.com/UAA-FlywayMigrationRunner-0.0.0-all.jar

**Comment by tylerphelan** [comment]
This did not seem to be an issue with the test jar after fixing the FAT format issue

**Comment by matthewmcnew** [comment]
I believe this might only be an issue on case insensitive filesystems where there is a conflict with LICENSE & license/some-file. This shouldn't be an issue during our build-init because it will run with a case sensitive filesystem. 

Might be something to keep in mind when we run consider windows support.

**Comment by mgibson1121** [comment]
This story passes acceptance with the JAR provided.
