### ISSUE TITLE
cronbuild

### ISSUE THREAD

**Issue by kfox1111** [pivotal/kpack#520]
It would be great if there was an equivalent of a Kubernetes CronJob for Builds so that it will periodically submit Builds to keep things up to date.

**Comment by matthewmcnew** [comment]
Hi @kfox1111 , Thanks for the suggestion. The kpack Image resource will automatically schedule builds when there are updates to dependencies (buildpacks/stacks/application source). Because builds will only be scheduled when there are known updates it should prevent unnecessary rebuilds. Is there a specific scenario you are concerned about?

**Comment by kfox1111** [comment]
Oh, cool. I didn't realize it would do that. Thanks. :)
