### ISSUE TITLE
ClusterStack & ClusterStore support using a private registry.

### ISSUE THREAD

**Issue by genevieve** [pivotal/kpack#649]
While using the `ClusterStack` resource in our cluster (in order to use it with the builder resource), we discovered that the CRD does not support using images from a private registry. For the `Build`/`Image` resources, we can point to our builder image in that same private registry as the creds are wired up fine and the controller can access the image.

```
{"level":"error","ts":"2021-03-16T21:58:11.929Z","logger":"controller.Stacks","caller":"controller/controller.go:480","msg":"Reconcile error","commit":"d4de54b","error":"GET https://repo-url: UNAUTHORIZED: access to the requested resource is not authorized","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\t/workspace/vendor/knative.dev/pkg/controller/controller.go:480\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/workspace/vendor/knative.dev/pkg/controller/controller.go:466\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\t/workspace/vendor/knative.dev/pkg/controller/controller.go:403"}
```

From [this conversation](https://buildpacks.slack.com/archives/CQ10WHMT4/p1616093428003200) it sounds like the issue is figuring out how to provide `imagePullSecrets` to these cluster scoped resources. I don't currently have a solution for modeling this and wanted to open this issue so we can track discussions around this feature.

**Comment by c0d1ngm0nk3y** [comment]
We would like to tackle this issue since we have the same use case.

Our proposal is first to introduce a `Stack` and a `Store` (namespaced) with a `serviceAccount`  (just like `Builder`).
This would allow the controllers to load the keychain from the respective `ServiceAccount` and pull from a private registry.
A `Builder` can then reference either a `Stack` or a `ClusterStack`. Some for `Store`/`ClusterStore`.

Any remarks, notes, objections ?

Tagging my pair: @Haegi

**Comment by c0d1ngm0nk3y** [comment]
@genevieve Would introducing a `Stack` und `Store` with a `serviceAccount` property work for you as well?

**Comment by genevieve** [comment]
This would work for us. Thanks @c0d1ngm0nk3y

**Comment by tarzzz** [comment]
Great work! Is there a timeline for when this will be available in a release?
