### ISSUE TITLE
Set a timeout on the builds 

### ISSUE THREAD

**Issue by samj1912** [pivotal/kpack#866]
Currently it's possible for a malicious actor or an improper dependency downloaded by a buildpack to create a cluster DoS attack by hoarding resources and resulting in a never ending build. kpack should expose active deadline seconds as a way to kill builds that take longer than a certain amount.

**Comment by tomkennedy513** [comment]
Could this be mitigated by the resource limits/quotas to prevent any particular pod from hogging too much. I feel like this issue is unlikely because of the testing provided by Paketo buildpacks in regards to their dependencies and the fact that a bad actor that can create an image or build would be able to set the timeout for that image or build. That being said I would be curious to hear more about how this issue came up and if this is something that we should attempt to solve, potentially with your proposed solution.

**Comment by tomkennedy513** [comment]
It seems that this happening accidentally is almost more likely simply because of the mitigations a cluster operator can take on the resource usage side. I can see this being valuable for the case that there is no way to cancel a build that is hanging without deleting it, but then you lose that history, which might be useful for identifying issues over time.

**Comment by tomkennedy513** [comment]
Is this something you experienced during your usage of kpack or is this more theoretical?

**Comment by tomkennedy513** [comment]
Do you see this being more valuable as a field on the image spec or a config that an operator can set cluster or namespace wide?
